CREATE TABLE blogful_users (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fullname TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  date_created TIMESTAMP NOT NULL DEFAULT now(),
  password TEXT,
  nickname TEXT
);
